
from collections import defaultdict
from flags import *

CHARACTER_FLAGS = defaultdict(int)

for code in range(ord('A'), ord('Z') + 1):
    CHARACTER_FLAGS[chr(code)] |= LINE_ASCENDS | LINE_HAS_UPPER_CASE

for code in range(ord('a'), ord('z') + 1):
    CHARACTER_FLAGS[chr(code)] |= LINE_HAS_LOWER_CASE

for code in range(ord('0'), ord('9') + 1):
    CHARACTER_FLAGS[chr(code)] |= LINE_HAS_DIGITS


CHARACTER_FLAGS['b'] |= LINE_ASCENDS
CHARACTER_FLAGS['d'] |= LINE_ASCENDS
CHARACTER_FLAGS['f'] |= LINE_ASCENDS
CHARACTER_FLAGS['g'] |= LINE_DESCENDS
CHARACTER_FLAGS['h'] |= LINE_ASCENDS
CHARACTER_FLAGS['i'] |= LINE_ASCENDS
CHARACTER_FLAGS['j'] |= LINE_DESCENDS
CHARACTER_FLAGS['k'] |= LINE_ASCENDS
CHARACTER_FLAGS['l'] |= LINE_ASCENDS
CHARACTER_FLAGS['p'] |= LINE_DESCENDS
CHARACTER_FLAGS['q'] |= LINE_DESCENDS
CHARACTER_FLAGS['t'] |= LINE_ASCENDS
CHARACTER_FLAGS['y'] |= LINE_DESCENDS

CHARACTER_FLAGS['!'] |= LINE_ASCENDS
CHARACTER_FLAGS['#'] |= LINE_ASCENDS
CHARACTER_FLAGS['$'] |= LINE_ASCENDS
CHARACTER_FLAGS['%'] |= LINE_ASCENDS
CHARACTER_FLAGS['&'] |= LINE_ASCENDS
CHARACTER_FLAGS['('] |= LINE_ASCENDS
CHARACTER_FLAGS[')'] |= LINE_ASCENDS
CHARACTER_FLAGS['*'] |= LINE_ASCENDS
CHARACTER_FLAGS['/'] |= LINE_ASCENDS
CHARACTER_FLAGS['?'] |= LINE_ASCENDS
CHARACTER_FLAGS['@'] |= LINE_ASCENDS
CHARACTER_FLAGS['['] |= LINE_ASCENDS
CHARACTER_FLAGS['\\'] |= LINE_ASCENDS
CHARACTER_FLAGS[']'] |= LINE_ASCENDS
CHARACTER_FLAGS['^'] |= LINE_ASCENDS
CHARACTER_FLAGS['{'] |= LINE_ASCENDS
CHARACTER_FLAGS['}'] |= LINE_ASCENDS

